// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "../src/LionVM.sol";

// Verifies that bytes produced by the lionlang/evm TypeScript encoder
// decode and execute correctly inside the Solidity LionVM. The fixture
// is generated by `packages/evm/scripts/generate-fixture.ts`.
contract WireFormatTest is Test {
    LionVM vm_;

    function setUp() public {
        vm_ = new LionVM();
    }

    function _load(string memory key) internal view returns (bytes memory) {
        string memory json = vm.readFile("test/fixtures/programs.json");
        return vm.parseJsonBytes(json, string.concat(".", key));
    }

    function _expectInt(bytes memory result, int256 want) internal pure {
        require(uint8(result[0]) == 0x01, "not int");
        int256 got;
        assembly { got := mload(add(result, 33)) }
        require(got == want, "int mismatch");
    }

    function test_Wire_Arithmetic() public {
        bytes memory program = _load("arithmetic");
        bytes memory result = vm_.execute(program);
        _expectInt(result, 6);
    }

    function test_Wire_Factorial6() public {
        bytes memory program = _load("factorial6");
        bytes memory result = vm_.execute(program);
        _expectInt(result, 720);
    }

    function test_Wire_Closure() public {
        bytes memory program = _load("closure");
        bytes memory result = vm_.execute(program);
        _expectInt(result, 15);
    }
}
